import { cp, mkdir, readFile, writeFile, access } from "fs/promises";
import { readFileSync } from "fs";
import { join, basename, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export function getPackageVersion(): string {
  const pkgPath = join(__dirname, "..", "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
  return pkg.version;
}

export function getBmadDir(): string {
  return join(__dirname, "..", "bmad");
}

export function getRalphDir(): string {
  return join(__dirname, "..", "ralph");
}

export function getSlashCommandsDir(): string {
  return join(__dirname, "..", "slash-commands");
}

export interface UpgradeResult {
  updatedPaths: string[];
}

export async function copyBundledAssets(projectDir: string): Promise<UpgradeResult> {
  const bmadDir = getBmadDir();
  const ralphDir = getRalphDir();
  const slashCommandsDir = getSlashCommandsDir();

  // Validate source directories exist
  try {
    await access(bmadDir);
  } catch {
    throw new Error(`BMAD source directory not found at ${bmadDir}. Package may be corrupted.`);
  }
  try {
    await access(ralphDir);
  } catch {
    throw new Error(`Ralph source directory not found at ${ralphDir}. Package may be corrupted.`);
  }
  try {
    await access(slashCommandsDir);
  } catch {
    throw new Error(`Slash commands directory not found at ${slashCommandsDir}. Package may be corrupted.`);
  }

  // Copy BMAD files → _bmad/
  await cp(bmadDir, join(projectDir, "_bmad"), { recursive: true });

  // Generate combined manifest from module-help.csv files
  await generateManifests(projectDir);

  // Generate _bmad/config.yaml
  const projectName = await deriveProjectName(projectDir);
  await writeFile(
    join(projectDir, "_bmad/config.yaml"),
    `# BMAD Configuration - Generated by bmalph
platform: claude-code
project_name: ${projectName}
output_folder: _bmad-output
user_name: BMad
communication_language: English
document_output_language: English
user_skill_level: intermediate
planning_artifacts: _bmad-output/planning-artifacts
implementation_artifacts: _bmad-output/implementation-artifacts
project_knowledge: docs
modules:
  - bmm
`,
  );

  // Copy Ralph templates → .ralph/
  await mkdir(join(projectDir, ".ralph"), { recursive: true });
  await cp(
    join(ralphDir, "templates/PROMPT.md"),
    join(projectDir, ".ralph/PROMPT.md"),
  );
  await cp(
    join(ralphDir, "templates/AGENT.md"),
    join(projectDir, ".ralph/@AGENT.md"),
  );

  // Copy Ralph loop and lib → .ralph/
  // Add version marker to ralph_loop.sh
  const loopContent = await readFile(join(ralphDir, "ralph_loop.sh"), "utf-8");
  const markerLine = `# bmalph-version: ${getPackageVersion()}`;
  const markedContent = loopContent.includes("# bmalph-version:")
    ? loopContent.replace(/# bmalph-version: .+/, markerLine)
    : loopContent.replace(/^(#!.+\r?\n)/, `$1${markerLine}\n`);
  await writeFile(join(projectDir, ".ralph/ralph_loop.sh"), markedContent);
  await cp(join(ralphDir, "lib"), join(projectDir, ".ralph/lib"), { recursive: true });

  // Install slash command → .claude/commands/bmalph.md
  await mkdir(join(projectDir, ".claude/commands"), { recursive: true });
  await cp(
    join(slashCommandsDir, "bmalph.md"),
    join(projectDir, ".claude/commands/bmalph.md"),
  );

  // Update .gitignore
  await updateGitignore(projectDir);

  return {
    updatedPaths: [
      "_bmad/",
      ".ralph/ralph_loop.sh",
      ".ralph/lib/",
      ".ralph/PROMPT.md",
      ".ralph/@AGENT.md",
      ".claude/commands/bmalph.md",
      ".gitignore",
    ],
  };
}

export async function installProject(projectDir: string): Promise<void> {
  // Create user directories (not overwritten by upgrade)
  await mkdir(join(projectDir, "bmalph/state"), { recursive: true });
  await mkdir(join(projectDir, ".ralph/specs"), { recursive: true });
  await mkdir(join(projectDir, ".ralph/logs"), { recursive: true });
  await mkdir(join(projectDir, ".ralph/docs/generated"), { recursive: true });

  await copyBundledAssets(projectDir);
}

async function deriveProjectName(projectDir: string): Promise<string> {
  try {
    const configPath = join(projectDir, "bmalph/config.json");
    const raw = await readFile(configPath, "utf-8");
    const config = JSON.parse(raw);
    if (config.name) return config.name;
  } catch {
    // config.json doesn't exist or is invalid — fall through
  }
  return basename(projectDir);
}

async function generateManifests(projectDir: string): Promise<void> {
  const configDir = join(projectDir, "_bmad/_config");
  await mkdir(configDir, { recursive: true });

  const coreHelpPath = join(projectDir, "_bmad/core/module-help.csv");
  const bmmHelpPath = join(projectDir, "_bmad/bmm/module-help.csv");

  const coreContent = await readFile(coreHelpPath, "utf-8");
  const bmmContent = await readFile(bmmHelpPath, "utf-8");

  // Extract header from core (first line) and data lines from both
  const coreLines = coreContent.trimEnd().split(/\r?\n/);
  const bmmLines = bmmContent.trimEnd().split(/\r?\n/);

  const header = coreLines[0];
  const coreData = coreLines.slice(1).filter((l) => l.trim());
  const bmmData = bmmLines.slice(1).filter((l) => l.trim());

  const combined = [header, ...coreData, ...bmmData].join("\n") + "\n";

  await writeFile(join(configDir, "task-manifest.csv"), combined);
  await writeFile(join(configDir, "workflow-manifest.csv"), combined);
}

async function updateGitignore(projectDir: string): Promise<void> {
  const gitignorePath = join(projectDir, ".gitignore");
  let existing = "";

  try {
    existing = await readFile(gitignorePath, "utf-8");
  } catch {
    // File doesn't exist, start fresh
  }

  const entries = [".ralph/logs/", "_bmad-output/"];
  const newEntries = entries.filter((e) => !existing.includes(e));

  if (newEntries.length === 0) return;

  const suffix =
    existing.length > 0 && !existing.endsWith("\n")
      ? "\n" + newEntries.join("\n") + "\n"
      : newEntries.join("\n") + "\n";

  await writeFile(gitignorePath, existing + suffix);
}

export async function mergeClaudeMd(projectDir: string): Promise<void> {
  const claudeMdPath = join(projectDir, "CLAUDE.md");
  const snippet = `
## BMAD-METHOD Integration

Use \`/bmalph\` to see your current phase and available commands.
Use \`/bmalph\` again when ready to advance to the next phase.
Use \`bmalph status\` for a quick overview of project phase and Ralph state.

### One-time setup

Run \`bmalph init\` to initialize the project.

### Transition to implementation

Run \`bmalph implement\` to convert planning artifacts to Ralph format and start the implementation loop.
`;

  let existing = "";
  try {
    existing = await readFile(claudeMdPath, "utf-8");
  } catch {
    // File doesn't exist, that's fine
  }

  if (existing.includes("## BMAD-METHOD Integration")) {
    return; // Already merged
  }

  await writeFile(claudeMdPath, existing + snippet);
}

export async function isInitialized(projectDir: string): Promise<boolean> {
  try {
    await access(join(projectDir, "bmalph/config.json"));
    return true;
  } catch {
    return false;
  }
}
